name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install packages
      run: sudo apt-get install libxslt-dev

    - name: Checkout Build
      uses: actions/checkout@v2

    - name: Install dependencies
      run: bundle install

    - name: Build
      if: github.ref != 'refs/heads/master'
      run: bundle exec jekyll build

    - name: Build & Algolia
      if: github.ref == 'refs/heads/master'
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      run: bundle exec jekyll algolia push
