name: Core Weekly

on:
  schedule:
    - cron:  '0 7 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set variable LAST_WEEK_NUM
      run: echo "LAST_WEEK_NUM=`date -d 'last week' +"%U"`" >> $GITHUB_ENV

    - name: Set variable YEAR
      run: echo "YEAR=`date -d 'last week' +"%Y"`" >> $GITHUB_ENV

    - name: Checkout Build
      uses: actions/checkout@v2

    - name: Fetch Core Weekly Generator
      run: git clone https://github.com/PrestaShop/core-weekly-generator.git ~/core-weekly-generator

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: cd ~/core-weekly-generator && pip install -r requirements.txt

    - name: Generate Core Weekly for the current week
      run: cd ~/core-weekly-generator && python core-weekly.py --week ${{ env.LAST_WEEK_NUM }} > $GITHUB_WORKSPACE/news/_posts/core-weekly/$(date +"%Y-%m-%d-coreweekly-${{ env.LAST_WEEK_NUM }}-%Y.md")

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Added Core Weekly ${{ env.LAST_WEEK_NUM }} of ${{ env.YEAR }}
        committer: PrestonBot <noreply@github.com>
        author: prestonBot <prestonBot@users.noreply.github.com>
        title: 'Added Core Weekly ${{ env.LAST_WEEK_NUM }} of ${{ env.YEAR }}'
        body: Added Core Weekly ${{ env.LAST_WEEK_NUM }} of ${{ env.YEAR }}
        base: 'master'
        delete-branch: true
